// ==================================================
// QUIZ INTERACTIF — TCHATCHIBARA-WEB School
// ==================================================

const QUIZ = [
    // ============ MATHS ============
    { id:1, matiere:"Mathématiques", classe:"3ème",
      question:"Dans un triangle rectangle, le carré de l'hypoténuse est égal à :",
      propositions:["La somme des carrés des 2 autres côtés","La différence des carrés","Le produit des 2 autres côtés","Le double du plus grand côté"],
      bonne:0,
      explication:"Théorème de Pythagore : BC² = AB² + AC²." },
    { id:2, matiere:"Mathématiques", classe:"2nde",
      question:"Le discriminant Δ de ax²+bx+c est :",
      propositions:["b² - 4ac","b² + 4ac","4ac - b²","-b/2a"],
      bonne:0,
      explication:"Δ = b² - 4ac. Il détermine le nombre de solutions." },
    { id:3, matiere:"Mathématiques", classe:"1ère",
      question:"La dérivée de x³ est :",
      propositions:["3x²","x²","3x","x⁴/4"],
      bonne:0,
      explication:"(x^n)' = n·x^(n-1), donc (x³)' = 3x²." },
    { id:4, matiere:"Mathématiques", classe:"Terminale",
      question:"∫₀¹ 2x dx = ?",
      propositions:["1","2","0","1/2"],
      bonne:0,
      explication:"[x²]₀¹ = 1 - 0 = 1." },
    { id:5, matiere:"Mathématiques", classe:"Terminale",
      question:"|3 + 4i| = ?",
      propositions:["5","7","25","√7"],
      bonne:0,
      explication:"|z| = √(3² + 4²) = √25 = 5." },

    // ============ PHYSIQUE-CHIMIE ============
    { id:6, matiere:"Physique-Chimie", classe:"3ème",
      question:"La loi d'Ohm s'écrit :",
      propositions:["U = R × I","U = R / I","U = I / R","U = R + I"],
      bonne:0,
      explication:"Tension = Résistance × Intensité." },
    { id:7, matiere:"Physique-Chimie", classe:"1ère",
      question:"1 m/s = combien de km/h ?",
      propositions:["3,6","0,36","36","1"],
      bonne:0,
      explication:"On multiplie par 3,6 : 1 m/s = 3,6 km/h." },
    { id:8, matiere:"Physique-Chimie", classe:"2nde",
      question:"L'eau bout à quelle température (pression normale) ?",
      propositions:["100°C","0°C","50°C","120°C"],
      bonne:0,
      explication:"L'eau bout à 100°C et gèle à 0°C." },

    // ============ SVT ============
    { id:9, matiere:"SVT", classe:"Terminale",
      question:"La synthèse des protéines se fait par :",
      propositions:["Transcription puis traduction","Réplication puis transcription","Mitose","Méiose"],
      bonne:0,
      explication:"ADN → ARNm (transcription) → protéine (traduction)." },
    { id:10, matiere:"SVT", classe:"2nde",
      question:"Quel organite produit l'énergie de la cellule ?",
      propositions:["La mitochondrie","Le noyau","Le ribosome","L'appareil de Golgi"],
      bonne:0,
      explication:"La mitochondrie est la centrale énergétique de la cellule." },

    // ============ FRANÇAIS ============
    { id:11, matiere:"Français", classe:"Toutes",
      question:"Combien d'étapes comporte un récit classique ?",
      propositions:["5","3","7","4"],
      bonne:0,
      explication:"Situation initiale, élément déclencheur, péripéties, dénouement, situation finale." },
    { id:12, matiere:"Français", classe:"Toutes",
      question:"Un narrateur qui dit 'je' est :",
      propositions:["Interne","Externe","Omniscient","Absent"],
      bonne:0,
      explication:"Le 'je' indique un narrateur interne (focalisation interne)." },

    // ============ PHILOSOPHIE ============
    { id:13, matiere:"Philosophie", classe:"Terminale",
      question:"Qui a dit : « L'homme est condamné à être libre » ?",
      propositions:["Sartre","Descartes","Platon","Kant"],
      bonne:0,
      explication:"Jean-Paul Sartre, dans 'L'Être et le Néant'." },
    { id:14, matiere:"Philosophie", classe:"Terminale",
      question:"Le cogito (« Je pense donc je suis ») est de :",
      propositions:["Descartes","Nietzsche","Spinoza","Aristote"],
      bonne:0,
      explication:"René Descartes, dans le 'Discours de la méthode' (1637)." },

    // ============ ROMAN ============
    { id:15, matiere:"Roman", classe:"Toutes",
      question:"Quel est le premier roman africain (Prix Goncourt 1921) ?",
      propositions:["Batouala","L'Enfant noir","Une si longue lettre","Le Devoir de violence"],
      bonne:0,
      explication:"'Batouala' de René Maran, Prix Goncourt 1921." },
    { id:16, matiere:"Roman", classe:"Toutes",
      question:"Qui a écrit 'Une si longue lettre' ?",
      propositions:["Mariama Bâ","Aminata Sow Fall","Angèle Rawiri","Calixte Beyala"],
      bonne:0,
      explication:"Mariama Bâ, écrivaine sénégalaise (1979)." },
    { id:17, matiere:"Roman", classe:"Toutes",
      question:"Le retour en arrière dans un récit s'appelle :",
      propositions:["Analepse (flashback)","Prolapse","Ellipse","Pause"],
      bonne:0,
      explication:"L'analepse raconte des événements antérieurs au moment présent du récit." },

    // ============ ARTS PLASTIQUES ============
    { id:18, matiere:"Arts Plastiques", classe:"Toutes",
      question:"Quelles sont les 3 couleurs primaires ?",
      propositions:["Rouge, bleu, jaune","Rouge, vert, bleu","Jaune, orange, violet","Noir, blanc, gris"],
      bonne:0,
      explication:"Les primaires ne s'obtiennent par aucun mélange." },
    { id:19, matiere:"Arts Plastiques", classe:"Toutes",
      question:"Les masques Punu du Gabon sont caractérisés par :",
      propositions:["Un visage blanc aux traits fins","Un visage en cuivre","Un visage en bois noir","Un visage peint en rouge"],
      bonne:0,
      explication:"Les masques Punu ont un visage blanc, des yeux mi-clos et une coiffure élaborée." },
    { id:20, matiere:"Arts Plastiques", classe:"Toutes",
      question:"La technique de peinture transparente est :",
      propositions:["L'aquarelle","La gouache","L'acrylique","L'huile"],
      bonne:0,
      explication:"L'aquarelle est transparente et se travaille avec de l'eau." },

    // ============ HISTOIRE-GÉO ============
    { id:21, matiere:"Histoire-Géo", classe:"4ème",
      question:"Quels étaient les 2 grands empires africains du Moyen Âge ?",
      propositions:["Ghana et Mali","Égypte et Nubie","Carthage et Rome","Songhaï et Kongo"],
      bonne:0,
      explication:"Ghana (VIIIe-XIe) et Mali (XIIIe-XVe) dominaient le commerce transsaharien." },
    { id:22, matiere:"Histoire-Géo", classe:"3ème",
      question:"En quelle année le Gabon est-il devenu indépendant ?",
      propositions:["1960","1958","1962","1955"],
      bonne:0,
      explication:"Le Gabon a accédé à l'indépendance le 17 août 1960." },

    // ============ ÉCONOMIE ============
    { id:23, matiere:"Économie", classe:"Terminale",
      question:"Que mesure le PIB ?",
      propositions:["La richesse produite dans un pays","Le taux de chômage","L'inflation","La dette publique"],
      bonne:0,
      explication:"Le PIB = Produit Intérieur Brut, mesure la production totale d'un pays." }
];
